import Link from 'next/link';
import {notFound} from 'next/navigation';
import {formatMarketCap,formatPrice,getMarket,getMarketCompanySync,getMarketCompanies,rankMarketCompanies} from '@/lib/markets/registry';

function resolveSegments(segments:string[]){return segments.length===1?{country:'EG',ticker:segments[0]}:segments.length===2?{country:segments[0],ticker:segments[1]}:null;}

export async function generateMetadata({params}:{params:Promise<{segments:string[]}>}){
  const resolved=resolveSegments((await params).segments);if(!resolved)return {title:'Company · EGYstocks'};const market=getMarket(resolved.country);const company=getMarketCompanySync(resolved.country,resolved.ticker);
  return {title:company?`${company.name} (${company.ticker}) · ${market.config.countryName} · EGYstocks`:`Company · ${market.config.countryName} · EGYstocks`,description:company?`${company.name} (${company.ticker}) listed on the ${market.config.exchangeName}.`:undefined};
}

export default async function CompanyPage({params}:{params:Promise<{segments:string[]}>}){
  const resolved=resolveSegments((await params).segments);if(!resolved)notFound();const market=getMarket(resolved.country);const rows=rankMarketCompanies(await getMarketCompanies(resolved.country));const c=rows.find(x=>x.ticker.toUpperCase()===resolved.ticker.toUpperCase());if(!c)notFound();
  return <div className="shell"><header className="header"><Link href={`/?country=${market.config.countryCode}`} className="brand">EGYstocks</Link><Link href={`/?country=${market.config.countryCode}`} className="muted" style={{fontSize:12}}>Back to ranking</Link></header><main className="detail"><div className="eyebrow">{market.config.flag} {market.config.countryName} · {c.exchangeCode}</div><h1>{c.name}</h1><div className="sub" style={{fontSize:12}}>{c.ticker} · {c.sector??'—'} · {market.config.exchangeName}</div><div className="price" style={{marginTop:10}}>{formatPrice(c.price,market.config.currencyCode)} <span className={`change ${c.changePercent===undefined?'muted':c.changePercent>=0?'positive':'negative'}`}>{c.changePercent===undefined?'—':`${c.changePercent>0?'+':''}${c.changePercent.toFixed(2)}%`}</span></div><div className="detailGrid"><div><span className="sub">Rank</span><strong>{c.rank?`#${String(c.rank).padStart(2,'0')}`:'—'}</strong></div><div><span className="sub">Market cap</span><strong>{formatMarketCap(c.marketCapLocal,market.config.currencyCode)}</strong></div><div><span className="sub">USD market cap</span><strong>{formatMarketCap(c.marketCapUSD,'USD')}</strong></div><div><span className="sub">Shares outstanding</span><strong>{c.sharesOutstanding?c.sharesOutstanding.toLocaleString('en-US'):'—'}</strong></div></div><div className="chart"><div className="eyebrow">Price history</div><p className="muted">Historical chart becomes available when the configured market-data provider supplies daily history.</p></div><p className="sub" style={{marginTop:24,lineHeight:1.7}}>Data: {c.dataSource??market.config.dataSource}. {market.config.delay}. Last quote: {c.timestamp?new Intl.DateTimeFormat('en-GB',{timeZone:market.config.timezone,dateStyle:'medium',timeStyle:'short'}).format(new Date(c.timestamp)):'—'}. Missing provider values are shown as — rather than fabricated.</p></main></div>;
}
