'use client';

import {useMemo,useState} from 'react';
import type {ReactNode} from 'react';
import type {CompanyFinancialData,FinancialValue,HistoricalPricePoint,MarketCompany} from '@/lib/markets/types';
import {downsampleHistory,filterHistoryByRange} from '@/lib/company-chart-utils';

type Metric='Price'|'Market Cap'|'P/E'|'P/S'|'Revenue'|'Earnings'|'EPS';
type Range='1D'|'1W'|'1M'|'3M'|'6M'|'1Y'|'3Y'|'5Y'|'MAX';
const metrics:Metric[]=['Price','Market Cap','P/E','P/S','Revenue','Earnings','EPS'];
const ranges:Range[]=['1D','1W','1M','3M','6M','1Y','3Y','5Y','MAX'];

function fmt(value:number|undefined,maximumFractionDigits=2){if(value===undefined||!Number.isFinite(value))return '—';return value.toLocaleString('en-US',{maximumFractionDigits});}
function pct(value:number|undefined){return value===undefined||!Number.isFinite(value)?'—':`${(value*100).toFixed(2)}%`;}
function compact(value:number|undefined,currency='USD'){if(value===undefined||!Number.isFinite(value))return '—';const prefix=currency==='USD'?'$':currency?`${currency} `:'';const abs=Math.abs(value);if(abs>=1e12)return `${prefix}${(value/1e12).toFixed(2)}T`;if(abs>=1e9)return `${prefix}${(value/1e9).toFixed(2)}B`;if(abs>=1e6)return `${prefix}${(value/1e6).toFixed(0)}M`;return `${prefix}${Math.round(value).toLocaleString('en-US')}`;}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="intelSection"><div className="intelSectionTitle">{title}</div>{children}</section>}
function MetricGrid({items}:{items:Array<{label:string;value:string;note?:string}>}){return <div className="metricGrid">{items.map(item=><div className="metricCell" key={item.label}><span>{item.label}</span><strong className="mono">{item.value}</strong>{item.note&&<small>{item.note}</small>}</div>)}</div>}
function Missing({children='Not available'}){return <span className="missing">{children}</span>}
function fv(data:FinancialValue|undefined){return data?.value;}
function fvText(data:FinancialValue|undefined,currency?:string){const value=fv(data);if(value===undefined)return '—';return currency?`${currency} ${fmt(value)}`:fmt(value);}
function fvCompact(data:FinancialValue|undefined,currency:string){return compact(fv(data),currency);}
function note(data:FinancialValue|undefined){if(!data)return undefined;return `${data.methodology==='calculated'?'Calculated':'Provider supplied'}${data.period?` · ${data.period}`:''}`;}
function fV(data:FinancialValue|undefined){const value=fv(data);return value===undefined?'—':`${value.toFixed(2)}×`;}

function PriceChart({points,currency}:{points:HistoricalPricePoint[];currency:string}){if(points.length<2)return <div className="emptyChart"><div><strong>Historical price data unavailable</strong><p>The configured provider did not return enough valid observations for this company.</p></div></div>;const width=1000,height=330,padX=34,padY=28;const values=points.map(p=>p.close).filter((value):value is number=>Number.isFinite(value));const min=Math.min(...values),max=Math.max(...values),spread=max-min||Math.max(max*.02,1);const x=(i:number)=>padX+(i/(points.length-1))*(width-padX*2);const y=(v:number)=>height-padY-((v-min)/spread)*(height-padY*2);const line=points.map((p,i)=>`${x(i).toFixed(1)},${y(p.close).toFixed(1)}`).join(' ');const first=points[0],last=points.at(-1)!;const change=first.close!==0?((last.close-first.close)/first.close)*100:0;return <div className="realChartWrap"><div className="chartStats"><span>{currency} {fmt(min)} — {currency} {fmt(max)}</span><strong className={change>=0?'positive':'negative'}>{change>=0?'+':''}{change.toFixed(2)}%</strong></div><svg className="realChart" style={{width:'100%',height:330,display:'block'}} viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Historical stock price chart">{[0,1,2,3].map(i=>{const yy=padY+i*((height-padY*2)/3);return <line key={i} x1={padX} x2={width-padX} y1={yy} y2={yy} stroke="currentColor" opacity=".08"/>})}<polyline fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" points={line}/></svg><div className="chartAxis" style={{display:'flex',justifyContent:'space-between',fontSize:11,color:'var(--muted)'}}><span>{new Date(first.date).toLocaleDateString('en-GB',{month:'short',year:'numeric'})}</span><span>{new Date(last.date).toLocaleDateString('en-GB',{month:'short',year:'numeric'})}</span></div></div>;}

export default function CompanyIntelligence({company,history,financials,exchangeName,countryName,currency,lastUpdated,dataSource,delay,providerTicker,dataError}:{company:MarketCompany;history:HistoricalPricePoint[];financials?:CompanyFinancialData;exchangeName:string;countryName:string;currency:string;lastUpdated:string;dataSource:string;delay:string;providerTicker?:string;dataError?:string}){
  const [metric,setMetric]=useState<Metric>('Price');const [range,setRange]=useState<Range>('1Y');const [period,setPeriod]=useState<'Annual'|'Quarterly'>('Annual');const filteredHistory=useMemo(()=>downsampleHistory(filterHistoryByRange(history,range),600),[history,range]);const quote=company.price;const change=company.changePercent;const changeText=change===undefined?'—':`${change>0?'+':''}${change.toFixed(2)}%`;const hasPriceHistory=history.length>1;const f=financials;
  const financialRows:Array<[string,FinancialValue|undefined]>=[['Revenue',f?.incomeStatement.revenue],['Gross Profit',f?.incomeStatement.grossProfit],['Operating Income',f?.incomeStatement.operatingIncome],['EBITDA',f?.incomeStatement.ebitda],['Net Income',f?.incomeStatement.netIncome],['EPS',f?.incomeStatement.eps],['Cash',f?.balanceSheet.cash],['Total Debt',f?.balanceSheet.totalDebt],['Total Assets',f?.balanceSheet.totalAssets],['Total Liabilities',f?.balanceSheet.totalLiabilities],['Equity',f?.balanceSheet.equity],['Operating Cash Flow',f?.cashFlow.operatingCashFlow],['Capital Expenditure',f?.cashFlow.capitalExpenditure],['Free Cash Flow',f?.cashFlow.freeCashFlow]];
  return <div className="companyIntel"><div className="companyHero"><div className="companyHeroMain"><div className="eyebrow">{countryName} · {company.exchangeCode}</div><div className="companyHeroIdentity"><div className="companyHeroMark">{company.name.slice(0,2).toUpperCase()}</div><div><h1>{company.name}</h1><div className="companySubline">{company.ticker} · {company.sector??'—'} · {exchangeName}</div></div></div></div><div className="companyHeroQuote"><div className="heroPrice mono">{quote===undefined?'—':`${currency} ${fmt(quote)}`}</div><div className={change===undefined?'muted':change>=0?'positive':'negative'}>{changeText}</div></div></div>
    <div className="dataStatus"><span>● {delay}</span><span>Last updated {lastUpdated}</span><span>Source: {dataSource}</span>{providerTicker&&<span>Symbol: {providerTicker}</span>}</div>{dataError&&<div className="dataNote" style={{border:'1px solid var(--line)',padding:'12px 14px',marginTop:14}}><strong>Some provider data is unavailable.</strong> {dataError}</div>}
    <section className="intelChartPanel"><div className="chartHeader"><div><div className="intelSectionTitle">Historical intelligence</div><div className="chartMetricLabel">{metric}</div></div><div className="controlGroup">{ranges.map(r=><button type="button" key={r} className={range===r?'control active':'control'} onClick={()=>setRange(r)}>{r}</button>)}</div></div><div className="metricTabs">{metrics.map(m=><button type="button" key={m} className={metric===m?'metricTab active':'metricTab'} onClick={()=>setMetric(m)}>{m}</button>)}</div>{metric==='Price'?<PriceChart points={filteredHistory} currency={currency}/>:<div className="emptyChart"><div><strong>{metric} history unavailable</strong><p>No verified historical {metric.toLowerCase()} dataset is currently connected. Current {metric} data, where available, is shown below.</p></div></div>}{hasPriceHistory&&<div className="dataNote">{filteredHistory.length.toLocaleString('en-US')} observations shown · Historical prices supplied by {dataSource}.</div>}</section>
    <Section title="Key metrics"><MetricGrid items={[{label:'Market Cap',value:compact(company.marketCapLocal,currency),note:company.marketCapSource==='calculated'?'Calculated from price × shares':'Provider/snapshot'},{label:'USD Market Cap',value:compact(company.marketCapUSD,'USD')},{label:'Shares Outstanding',value:company.sharesOutstanding?.toLocaleString('en-US')??fvText(f?.shareholder.sharesOutstanding)},{label:'Previous Close',value:company.previousClose===undefined?'—':`${currency} ${fmt(company.previousClose)}`},{label:'Open',value:company.open===undefined?'—':`${currency} ${fmt(company.open)}`},{label:'High',value:company.high===undefined?'—':`${currency} ${fmt(company.high)}`},{label:'Low',value:company.low===undefined?'—':`${currency} ${fmt(company.low)}`},{label:'Volume',value:company.volume===undefined?'—':company.volume.toLocaleString('en-US')}]}/></Section>
    <Section title="Valuation"><MetricGrid items={[{label:'P/E',value:fV(f?.valuation.pe),note:note(f?.valuation.pe)},{label:'P/S',value:fV(f?.valuation.ps),note:note(f?.valuation.ps)},{label:'P/B',value:fV(f?.valuation.pb),note:note(f?.valuation.pb)},{label:'P/FCF',value:'—',note:'No verified provider value'},{label:'EV / Revenue',value:fV(f?.valuation.evRevenue),note:note(f?.valuation.evRevenue)},{label:'EV / EBITDA',value:fV(f?.valuation.evEbitda),note:note(f?.valuation.evEbitda)}]}/><p className="dataNote">Valuation values are provider-supplied and period-labelled. Missing values remain unavailable rather than being estimated.</p></Section>
    <Section title="Financial statements"><div className="periodBar"><button type="button" className={period==='Annual'?'period active':'period'} onClick={()=>setPeriod('Annual')}>Annual</button><button type="button" className={period==='Quarterly'?'period active':'period'} onClick={()=>setPeriod('Quarterly')}>Quarterly</button></div><div className="financialTableWrap"><table className="financialTable"><thead><tr><th>Metric</th><th>Value</th><th>Period</th><th>Currency</th></tr></thead><tbody>{financialRows.map(([label,data])=><tr key={label}><th>{label}</th><td>{data?fvCompact(data,currency):<Missing/>}</td><td>{data?.period??'—'}</td><td>{data?.currency??currency}</td></tr>)}</tbody></table></div><p className="dataNote">Source: {f?.source??'No verified fundamental provider'}. The current provider exposes TTM/MRQ fields for several metrics; the table never invents unavailable annual or quarterly observations.</p></Section>
    <Section title="Profitability"><MetricGrid items={[{label:'ROE',value:pct(fv(f?.profitability.roe)),note:note(f?.profitability.roe)},{label:'ROA',value:pct(fv(f?.profitability.roa)),note:note(f?.profitability.roa)},{label:'ROIC',value:pct(fv(f?.profitability.roic)),note:note(f?.profitability.roic)},{label:'Gross Margin',value:pct(fv(f?.incomeStatement.grossMargin))},{label:'Operating Margin',value:pct(fv(f?.incomeStatement.operatingMargin))},{label:'Net Margin',value:pct(fv(f?.incomeStatement.netMargin))}]}/></Section>
    <Section title="Balance sheet"><MetricGrid items={[{label:'Cash',value:fvCompact(f?.balanceSheet.cash,currency),note:note(f?.balanceSheet.cash)},{label:'Total Debt',value:fvCompact(f?.balanceSheet.totalDebt,currency)},{label:'Net Debt',value:fvCompact(f?.balanceSheet.netDebt,currency),note:note(f?.balanceSheet.netDebt)},{label:'Total Assets',value:fvCompact(f?.balanceSheet.totalAssets,currency)},{label:'Total Liabilities',value:fvCompact(f?.balanceSheet.totalLiabilities,currency)},{label:"Shareholders' Equity",value:fvCompact(f?.balanceSheet.equity,currency)},{label:'Book Value',value:fvCompact(f?.balanceSheet.bookValue,currency)},{label:'Book Value / Share',value:fvText(f?.balanceSheet.bookValuePerShare,currency)}]}/></Section>
    <Section title="Cash flow"><MetricGrid items={[{label:'Operating Cash Flow',value:fvCompact(f?.cashFlow.operatingCashFlow,currency)},{label:'Capital Expenditure',value:fvCompact(f?.cashFlow.capitalExpenditure,currency)},{label:'Free Cash Flow',value:fvCompact(f?.cashFlow.freeCashFlow,currency)},{label:'FCF Margin',value:pct(fv(f?.cashFlow.fcfMargin))}]}/></Section>
    <Section title="Shareholder data"><MetricGrid items={[{label:'Shares Outstanding',value:company.sharesOutstanding?.toLocaleString('en-US')??fvText(f?.shareholder.sharesOutstanding)},{label:'Dividend / Share',value:fvText(f?.shareholder.dividendPerShare,currency)},{label:'Dividend Yield',value:pct(fv(f?.shareholder.dividendYield))},{label:'Payout Ratio',value:pct(fv(f?.shareholder.payoutRatio))},{label:'Buybacks',value:'—',note:'No verified provider value'}]}/></Section>
  </div>;
}
