import type {BoycottCategory,BoycottEntry,BoycottVisibility} from './types';

export const SOURCE_URL='https://www.is-boycott.com/en/all/companies';
export const WHO_PROFITS_URL='https://www.is-boycott.com/en/lists/who-profits';
export const BDS_URL='https://bdsmovement.net/Guide-to-BDS-Boycott';
export const SOURCE_LABEL='Is-Boycott company database';
export const DATASET_POLICY='Company inclusion is source-backed. Visibility is an editorial consumer-prominence ranking, not audited North-African sales data. BDS classifications are kept separate from independent databases and research lists.';
const SOURCE_MINIMUM_EXPECTED=400;
const CACHE_TTL=21600000;
let memoryCache:{expiresAt:number;entries:BoycottEntry[]}|null=null;

export const CATEGORY_LABELS:Record<BoycottCategory,string>={food:'Food & Restaurants',beverages:'Beverages',grocery:'Grocery & Supermarkets',fashion:'Fashion & Clothing',beauty:'Beauty & Personal Care',household:'Household',baby:'Baby & Family',technology:'Technology',software:'Software & Internet',finance:'Finance & Banking',travel:'Travel & Hospitality',automotive:'Transportation & Automotive',energy:'Energy',media:'Entertainment & Media',healthcare:'Healthcare & Pharmaceuticals',industrial:'Industrial',construction:'Construction & Real Estate',agriculture:'Agriculture',logistics:'Logistics',retail:'Retail',other:'Other'};

const VISIBILITY_ORDER=["McDonald's",'Coca-Cola','Starbucks','Carrefour','Burger King','PepsiCo','Nestlé','ZARA','Microsoft','Google','Amazon','Disney','Sony Corporation','Puma','Reebok','Hewlett Packard (HP & HP-E)','Dell','Intel','Ford Motor Company','Toyota Motor Corporation','Volkswagen Group','Pizza Hut',"Papa John's",'Airbnb','Booking.com','Booking Holdings','Expedia Group','TripAdvisor','Wix','YouTube','Xbox','OpenAI','GitHub','LinkedIn','Oracle','IBM','Cisco','Motorola Solutions','Siemens AG','Chevron','BP PLC','Barclays','J.C. Bamford Excavators (JCB)','Caterpillar','Volvo Group','General Motors Company','Mitsubishi Motors Corporation','Jaguar Land Rover Automotive PLC','FANUC Corporation','Maersk (Mærsk)','Spotify','Stradivarius','Massimo Dutti','Pull & Bear','Bershka','Oysho','Lefties','Swarovski','Forever 21','Nautica','Roxy','Volcom','KAYAK','Hotels.com','OpenTable','ExpressVPN','Vercel','Waze','DeepMind','Palantir Technologies'];
const VISIBILITY_SCORE=new Map(VISIBILITY_ORDER.map((name,index)=>[name,1000-index*10]));

const PRODUCT_LABELS:Record<string,string>={"McDonald's":"McDonald's",'Coca-Cola':'Coca-Cola','Starbucks':'Starbucks','Burger King':'Burger King','Carrefour':'Carrefour','PepsiCo':'Pepsi / PepsiCo','Nestlé':'Nestlé products','ZARA':'Zara','Microsoft':'Windows / Azure / Xbox','Google':'Google services','Amazon':'Amazon / AWS','Disney':'Disney','Sony Corporation':'Sony products','Puma':'Puma','Reebok':'Reebok','Dell':'Dell Technologies','Intel':'Intel','Ford Motor Company':'Ford','Toyota Motor Corporation':'Toyota','Volkswagen Group':'Volkswagen','Pizza Hut':'Pizza Hut',"Papa John's":"Papa John's",'Airbnb':'Airbnb','Booking.com':'Booking.com','Booking Holdings':'Booking','Expedia Group':'Expedia','TripAdvisor':'Tripadvisor','Wix':'Wix','YouTube':'YouTube','Xbox':'Xbox','OpenAI':'OpenAI','GitHub':'GitHub','LinkedIn':'LinkedIn','Oracle':'Oracle','IBM':'IBM','Cisco':'Cisco','Motorola Solutions':'Motorola Solutions','Siemens AG':'Siemens','Chevron':'Chevron','BP PLC':'BP','Barclays':'Barclays','Spotify':'Spotify','Waze':'Waze','Vercel':'Vercel'};

const BDS_CLASSIFICATION:Record<string,string>={'Chevron':'BDS — consumer priority target','Intel':'BDS — consumer priority target','Dell':'BDS — consumer priority target','Siemens AG':'BDS — consumer priority target','Hewlett Packard (HP & HP-E)':'BDS — consumer priority target',"McDonald's":'BDS — grassroots / organic campaign','Coca-Cola':'BDS — grassroots / organic campaign','Burger King':'BDS — grassroots / organic campaign',"Papa John's":'BDS — grassroots / organic campaign','Pizza Hut':'BDS — grassroots / organic campaign','Wix':'BDS — grassroots / organic campaign','Google':'BDS — pressure target','Amazon':'BDS — pressure target','Microsoft':'BDS — pressure target','Booking.com':'BDS — pressure target','Booking Holdings':'BDS — pressure target','Expedia Group':'BDS — pressure target','Airbnb':'BDS — pressure target'};
const BDS_REASONS:Record<string,string>={'Chevron':'BDS identifies Chevron as a consumer boycott priority target because of its documented role in extracting energy resources connected to Israel.','Intel':'BDS identifies Intel as a consumer boycott priority target because of its long-running operations and investment in Israel.','Dell':'BDS identifies Dell as a consumer boycott priority target and documents technology supplied to Israeli institutions.','Siemens AG':'BDS identifies Siemens as a consumer boycott priority target because of its role in the Euro-Asia electricity interconnector.','Hewlett Packard (HP & HP-E)':'BDS identifies HP/HPE as a consumer boycott priority target because of technology and services supplied to Israeli state institutions.',"McDonald's":"BDS supports the grassroots boycott campaign against McDonald's.",'Coca-Cola':'BDS supports the grassroots boycott campaign against Coca-Cola.','Burger King':'BDS supports the grassroots boycott campaign against Burger King.',"Papa John's":"BDS supports the grassroots boycott campaign against Papa John's.",'Pizza Hut':'BDS supports the grassroots boycott campaign against Pizza Hut.','Wix':'BDS supports the grassroots boycott campaign against WIX.','Google':'BDS calls for pressure on Google in connection with Project Nimbus and related technology services.','Amazon':'BDS calls for pressure on Amazon in connection with Project Nimbus and related technology services.','Microsoft':'BDS identifies Microsoft in its current pressure/divestment research context concerning technology services supplied to Israel.','Booking.com':'BDS identifies Booking.com as a pressure target because it lists properties in Israeli settlements.','Booking Holdings':'BDS identifies Booking Holdings as a pressure target because its services include settlement listings.','Expedia Group':'BDS identifies Expedia as a pressure target because it lists properties in Israeli settlements.','Airbnb':'BDS identifies Airbnb as a pressure target because it lists properties in Israeli settlements.'};

const BDS_FALLBACK_NAMES=['Airbnb','Amazon','AXA','Booking.com','Burger King','Caltex','Carrefour','Chevron','Coca-Cola','Dell','Disney','Elbit Systems','Expedia Group','Google','Hewlett Packard (HP & HP-E)','Intel',"McDonald's",'Palantir Technologies',"Papa John's",'Pizza Hut','Remax','Siemens AG','SodaStream','Spotify','Teva Pharmaceutical','Texaco','Wix','ZARA'];

const CATEGORY_RULES:Array<[BoycottCategory,RegExp]>=[['food',/mcdonald|burger|restaurant|pizza|starbucks|coffee|dunkin|caribou|hardee|domino|papa john|subway|wendy|taco|bakery|winery|nestl|purina|cereal|buitoni/i],['beverages',/coca.?cola|pepsi|red bull|nestle|aquafina|dasani|fanta|sprite|7up|mirinda|mountain dew|tempo beverage/i],['grocery',/carrefour|supermarket|grocery|shufersal|rami levy|spinneys|panda|metro|lulu|kazyon/i],['fashion',/zara|puma|reebok|fashion|clothing|pull.?bear|stradivarius|lefties|swarovski|quiksilver|volcom|roxy|bershka|massimo dutti|oysho|forever 21|nautica/i],['beauty',/l.?oreal|loreal|cerave|maybelline|garnier|dove|rexona|axe|vaseline|gillette|olay|pantene|schwarzkopf|neutrogena|beauty|cosmetic/i],['technology',/samsung|apple|sony|lg|toshiba|hp|dell|intel|microsoft|google|alphabet|meta|palantir|mobileye|hitachi|dji|technology|electronics|cisco|oracle|ibm|motorola|openai|github|vercel|wix|linkedin/i],['software',/github|vercel|linkedin|youtube|netflix|spotify|waze|wix|opentable|tripadvisor|trivago|software|cloud|vpn|cyberghost|xbox|deepmind/i],['finance',/bank|banking|insurance|pimco|ishares|etoro|barclays|finance|capital|axa/i],['travel',/booking|hotel|airbnb|expedia|orbitz|priceline|kayak|ebookers|hotels\.com|rentalcars|cheapflights|tripadvisor|travel|cruise|tui/i],['automotive',/toyota|volkswagen|ford|jaguar|land rover|mitsubishi|general motors|hyundai|volvo|automotive/i],['energy',/bp|chevron|caltex|exxon|mobil|solar|energix|renewable|energy|oil|gas|delek/i],['media',/disney|espn|politico|spotify|youtube|media|broadcast|publishing|morning brew/i],['healthcare',/teva|roche|bayer|pharmaceutical|pharma|medical|health|hospital|laborator/i],['industrial',/abb|fanuc|atlas copco|bomag|cnh|doosan|fassi|general electric|garrett|terex|liebher|manitou|industrial|systems/i],['construction',/building|construction|cement|materials|ashtrom|shapir|shikun|real estate|properties/i],['agriculture',/agro|fertilizer|grower|agriculture|rivulis|hadiklaim/i],['logistics',/maersk|zim|shipping|logistics|rail|egged/i],['retail',/retail|stores|market|shopping/i]];

function decodeHtml(value:string){return value.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&apos;/gi,"'").replace(/&#39;/gi,"'").replace(/&#x27;/gi,"'").replace(/&#x2F;/gi,'/').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)));}
function cleanCompanyName(value:string){let name=decodeHtml(value.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());name=name.replace(/\s*Company\s*$/i,'').trim();name=name.replace(/\s+\((?:🌐|[🇦-🇿]|Apartheid Israel|Israel|UK|US|Canada|Australia|Germany|France|Spain|Sweden|Netherlands|Switzerland|Belgium|Austria|Romania|Ireland|Iceland|Czech Republic|Italy|Norway)[^)]*\)$/iu,'').trim();return name;}
function slugify(value:string){return value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function inferCategory(company:string):BoycottCategory{for(const [category,pattern] of CATEGORY_RULES)if(pattern.test(company))return category;return 'other';}
function aliasesFor(company:string){const aliases:Record<string,string[]>={"Coca-Cola":['Coke','Coca Cola','كوكاكولا','كوكا كولا'],"McDonald's":['McDonalds','McD','ماكدونالدز','ماكدونالد'],'Google':['جوجل','غوغل'],'Hewlett Packard (HP & HP-E)':['HP','HPE','إتش بي'],'ZARA':['Zara','زارا'],'Starbucks':['ستاربكس'],'Carrefour':['كارفور'],'PepsiCo':['Pepsi','بيبسي']};return aliases[company]??[];}
function visibilityFor(company:string){const score=VISIBILITY_SCORE.get(company)??100;return {score,visibility:(score>=700?'very-high':score>=350?'high':score>=180?'medium':'low') as BoycottVisibility};}

function makeEntry(company:string,source:string,sourceUrl:string,extra?:Partial<BoycottEntry>):BoycottEntry{const canonical=cleanCompanyName(company);const {score,visibility}=visibilityFor(canonical);return {id:`source-${slugify(canonical)}`,rank:0,company:canonical,product:PRODUCT_LABELS[canonical]??'—',category:inferCategory(canonical),aliases:aliasesFor(canonical),reason:BDS_REASONS[canonical]??`The cited source documents this company in its boycott/research database. See the source for the underlying evidence and classification.`,status:'Documented source entry',source,sourceUrl,confidence:BDS_REASONS[canonical]?'high':'medium',campaignType:BDS_CLASSIFICATION[canonical]??'Independent research database entry',visibility,visibilityScore:score,...extra};}

function parseCompanyAnchors(html:string,source=SOURCE_LABEL,sourceUrl=SOURCE_URL){const matches=Array.from(html.matchAll(/<a[^>]+href=["'](\/en\/c\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi));const entries:BoycottEntry[]=[];const seen=new Set<string>();for(const match of matches){const company=cleanCompanyName(match[2]);if(!company||company.length<2)continue;const key=company.toLowerCase();if(seen.has(key))continue;seen.add(key);entries.push(makeEntry(company,source,sourceUrl));}return entries;}

function parseWhoProfits(html:string){const marker=/465 companies total/i;const markerIndex=html.search(marker);if(markerIndex<0)return [];const body=html.slice(markerIndex);const fragments=Array.from(body.matchAll(/>([^<>]{2,180})</g)).map(m=>decodeHtml(m[1].replace(/\s+/g,' ').trim()));const blocked=/^(Image:|Who Profits|About Us|Companies|Brands|Investment Firms|Venture Capitalists|Loading|Curated Lists|Search|Browse|The Who Profits|You can check|Previous|Next|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z)$/i;const seen=new Set<string>();const entries:BoycottEntry[]=[];for(const fragment of fragments){const company=cleanCompanyName(fragment);if(!company||blocked.test(company)||company.length<3||company.length>170)continue;if(!/[A-Za-z]/.test(company))continue;if(/^(List|View|Home|Contact|Donate|About|Company Name|Main Headquarters|Involvement)$/i.test(company))continue;const key=company.toLowerCase();if(seen.has(key))continue;seen.add(key);entries.push(makeEntry(company,'Who Profits Research Center list',WHO_PROFITS_URL,{campaignType:'Who Profits corporate involvement research'}));}return entries;}

function bdsFallback(){return BDS_FALLBACK_NAMES.map(name=>makeEntry(name,'BDS Priority List',BDS_URL,{campaignType:BDS_CLASSIFICATION[name]??'BDS / BNC priority list',reason:BDS_REASONS[name]??'Listed in the current BDS priority list; consult the official BDS source for the campaign rationale.',confidence:'high',status:'BDS documented target'}));}

function normalize(entries:BoycottEntry[]){const byName=new Map<string,BoycottEntry>();for(const entry of entries){const key=entry.company.toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ').trim();const existing=byName.get(key);if(!existing)byName.set(key,entry);else{existing.reason=existing.reason||entry.reason;existing.source=existing.source||entry.source;existing.sourceUrl=existing.sourceUrl||entry.sourceUrl;existing.campaignType=existing.campaignType=== 'Independent research database entry'?entry.campaignType:existing.campaignType;existing.confidence=existing.confidence==='high'?'high':entry.confidence??existing.confidence;}}return Array.from(byName.values()).sort((a,b)=>(b.visibilityScore??0)-(a.visibilityScore??0)||a.company.localeCompare(b.company)).map((entry,index)=>({...entry,rank:index+1}));}

async function fetchHtml(url:string){try{const response=await fetch(url,{cache:'no-store',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/153.0.0.0 Safari/537.36','accept':'text/html,application/xhtml+xml','accept-language':'en-US,en;q=0.9'}});return response.ok?await response.text():'';}catch{return '';}}

export async function getBoycottEntries():Promise<BoycottEntry[]>{
 if(memoryCache&&memoryCache.expiresAt>Date.now())return memoryCache.entries;
 const [allHtml,whoProfitsHtml]=await Promise.all([fetchHtml(SOURCE_URL),fetchHtml(WHO_PROFITS_URL)]);
 const liveAll=parseCompanyAnchors(allHtml);
 const liveWhoProfits=parseWhoProfits(whoProfitsHtml);
 const merged=normalize([...liveAll,...liveWhoProfits,bdsFallback()]);
 if(merged.length>=SOURCE_MINIMUM_EXPECTED){memoryCache={expiresAt:Date.now()+CACHE_TTL,entries:merged};return merged;}
 const safe=normalize([...liveWhoProfits,...liveAll,...bdsFallback()]);
 if(safe.length>0){memoryCache={expiresAt:Date.now()+CACHE_TTL,entries:safe};return safe;}
 return bdsFallback().map((entry,index)=>({...entry,rank:index+1}));
}

export const BOYCOTT_ENTRIES:BoycottEntry[]=[];
