import Link from 'next/link';
import {notFound} from 'next/navigation';
import {formatMarketCap,formatPrice,getMarket,getMarketCompanySync,rankMarketCompanies} from '@/lib/markets/registry';

export async function generateMetadata({params}:{params:Promise<{country:string;ticker:string}>}){
  const {country,ticker}=await params;const market=getMarket(country);const company=getMarketCompanySync(country,ticker);
  return {title:company?`${company.name} (${company.ticker}) · ${market.config.countryName} · EGYstocks`:`Company · ${market.config.countryName} · EGYstocks`,description:company?`${company.name} (${company.ticker}) listed on the ${market.config.exchangeName}.`:undefined};
}

export default async function CompanyPage({params}:{params:Promise<{country:string;ticker:string}>}){
  const {country,ticker}=await params;const market=getMarket(country);const company=getMarketCompanySync(country,ticker);if(!company)notFound();
  const rows=rankMarketCompanies(getMarketCompanySync(country)?[...((await import('@/lib/markets/registry')).getMarketCompaniesSync(country))]:[]);const c=rows.find(x=>x.ticker.toUpperCase()===ticker.toUpperCase())??company;
  return <div className="shell"><header className="header"><Link href={`/?country=${market.config.countryCode==='EG'?'EG':market.config.countryCode}`} className="brand">EGYstocks</Link><Link href={`/?country=${market.config.countryCode}`} className="muted" style={{fontSize:12}}>Back to ranking</Link></header><main className="detail"><div className="eyebrow">{market.config.flag} {market.config.countryName} · {market.config.exchangeCode}</div><h1>{c.name}</h1><div className="sub" style={{fontSize:12}}>{c.ticker} · {c.sector??'—'} · {market.config.exchangeName}</div><div className="price" style={{marginTop:10}}>{formatPrice(c.price,market.config.currencyCode)} <span className={`change ${c.changePercent===undefined?'muted':c.changePercent>=0?'positive':'negative'}`}>{c.changePercent===undefined?'—':`${c.changePercent>0?'+':''}${c.changePercent.toFixed(2)}%`}</span></div><div className="detailGrid"><div><span className="sub">Rank</span><strong>{c.rank?`#${String(c.rank).padStart(2,'0')}`:'—'}</strong></div><div><span className="sub">Market cap</span><strong>{formatMarketCap(c.marketCapLocal,market.config.currencyCode)}</strong></div><div><span className="sub">USD market cap</span><strong>{formatMarketCap(c.marketCapUSD,'USD')}</strong></div><div><span className="sub">Shares outstanding</span><strong>{c.sharesOutstanding?c.sharesOutstanding.toLocaleString('en-US'):'—'}</strong></div></div><div className="chart"><div className="eyebrow">Price history</div><p className="muted">Historical chart becomes available when the configured market-data provider supplies daily history.</p></div><p className="sub" style={{marginTop:24,lineHeight:1.7}}>Data: {market.config.dataSource}. {market.config.delay}. Market capitalization is shown from the configured market-data snapshot when available; missing values are shown as — rather than fabricated.</p></main></div>;
}
