import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {getCountryBySlug,SECTION_CONTENT,NORTH_AFRICA_COUNTRIES} from '@/lib/north-africa';
import styles from '@/components/north-africa-section-page.module.css';

export async function generateStaticParams(){return NORTH_AFRICA_COUNTRIES.flatMap(country=>country.availableSections.map(section=>({section,country:country.slug})))}
export async function generateMetadata({params}:{params:Promise<{section:string;country:string}>}):Promise<Metadata>{const {section,country:slug}=await params;const country=getCountryBySlug(slug);const content=SECTION_CONTENT[section];return country&&content?{title:`North Africa Hub | ${country.name} ${content.title}`,description:`${content.title} coverage for ${country.name} on North Africa Hub.`}:{title:'North Africa Hub',description:'North Africa Hub is a North Africa information and intelligence platform.'}}
export default async function CountrySectionPage({params}:{params:Promise<{section:string;country:string}>}){
 const {section,country:slug}=await params;const country=getCountryBySlug(slug);const content=SECTION_CONTENT[section];if(!country||!content)notFound();
 if(section==='markets'){if(!country.availableSections.includes('markets'))return <main className={styles.page}><div className={styles.breadcrumb}>North Africa / Stock Market / {country.name}</div><div className={styles.hero}><div><div className="eyebrow">{country.flag} {country.name}</div><h1>Stock Market</h1><p>Market coverage is not currently available for {country.name}.</p></div></div></main>;redirect(`/markets/${country.slug}`)}
 const supported=country.availableSections.includes(section);
 return <main className={styles.page}><div className={styles.breadcrumb}><Link href="/">North Africa</Link> / <Link href={`/${section}`}>{content.title}</Link> / {country.name}</div><div className={styles.hero}><div><div className="eyebrow">{country.flag} {country.name}</div><h1>{content.title}</h1><p>{supported?content.description:`${content.title} coverage for ${country.name} is being prepared.`}</p></div></div>{supported?<><section className={styles.overview}><div className="eyebrow">Section index</div><h2>{country.name} · {content.title}</h2><p>No unsupported facts are displayed yet. This page is ready for verified editorial and data content.</p></section><section className={styles.topics}><div className="eyebrow">Planned coverage</div><div className={styles.topicGrid}>{content.topics.map(topic=><div key={topic} className={styles.topic}><span>{topic}</span><small>Coming soon</small></div>)}</div></section></>:<section className={styles.coming}><strong>Coverage coming soon</strong><p>The platform architecture supports this country and section, but verified content is not connected yet.</p></section>}</main>;
}
