'use client';

import {useEffect,useMemo,useState} from 'react';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import type {BoycottCategory,BoycottEntry,BoycottVisibility} from '@/lib/boycott/types';
import {CATEGORY_LABELS} from '@/lib/boycott/data';
import styles from './boycott-explorer.module.css';

function normalize(value:string){return value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function initials(name:string){const words=name.trim().split(/\s+/).filter(Boolean);if(!words.length)return '—';if(words.length===1)return Array.from(words[0]).slice(0,2).join('').toUpperCase();return `${Array.from(words[0])[0]??''}${Array.from(words[1])[0]??''}`.toUpperCase();}
function visibilityLabel(value?:BoycottVisibility){return value==='very-high'?'Very high':value==='high'?'High':value==='medium'?'Medium':'Low';}
function Logo({entry}:{entry:BoycottEntry}){const [src,setSrc]=useState(entry.logo??'');const [failed,setFailed]=useState(false);useEffect(()=>{if(src||failed)return;let cancelled=false;fetch(`/api/logos?name=${encodeURIComponent(entry.company)}`,{cache:'force-cache'}).then(async response=>{if(!response.ok)throw new Error('logo');const data=await response.json() as {website?:string|null};if(!data.website)throw new Error('logo');if(!cancelled)setSrc(`https://cdn.tickerlogos.com/${data.website.replace(/^https?:\/\//,'').replace(/\/$/,'')}`);}).catch(()=>{if(!cancelled)setFailed(true);});return()=>{cancelled=true;};},[entry.company,failed,src]);return <span className={styles.logo}>{!failed&&src?<img src={src} alt="" loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>{setSrc('');setFailed(true)}}/>:<span aria-hidden="true">{initials(entry.company)}</span>}</span>;}
function categoryLabel(category?:BoycottCategory){return category?CATEGORY_LABELS[category]:'Other';}

export default function BoycottExplorer({entries}:{entries:BoycottEntry[]}){
 const router=useRouter();const pathname=usePathname();const searchParams=useSearchParams();
 const [search,setSearch]=useState(searchParams.get('search')??'');const [category,setCategory]=useState<BoycottCategory|'all'>((searchParams.get('category') as BoycottCategory|'all')??'all');const [campaign,setCampaign]=useState(searchParams.get('campaign')??'all');const [source,setSource]=useState(searchParams.get('source')??'all');const [visibility,setVisibility]=useState<BoycottVisibility|'all'>((searchParams.get('visibility') as BoycottVisibility|'all')??'all');const [sort,setSort]=useState(searchParams.get('sort')??'relevance');const [selected,setSelected]=useState<BoycottEntry|null>(null);
 const categories=useMemo(()=>Array.from(new Set(entries.map(e=>e.category??'other'))).sort((a,b)=>(CATEGORY_LABELS[a as BoycottCategory]??a).localeCompare(CATEGORY_LABELS[b as BoycottCategory]??b)),[entries]);
 const campaigns=useMemo(()=>Array.from(new Set(entries.map(e=>e.campaignType).filter(Boolean) as string[])).sort(),[entries]);
 const sources=useMemo(()=>Array.from(new Set(entries.map(e=>e.source).filter(Boolean) as string[])).sort(),[entries]);
 const normalizedSearch=normalize(search);
 const filtered=useMemo(()=>{const result=entries.filter(entry=>{const haystack=normalize([entry.company,entry.product,entry.reason,entry.category?CATEGORY_LABELS[entry.category]:'',entry.campaignType??'',entry.source??'',...(entry.aliases??[])].join(' '));return(!normalizedSearch||haystack.includes(normalizedSearch))&&(category==='all'||entry.category===category)&&(campaign==='all'||entry.campaignType===campaign)&&(source==='all'||entry.source===source)&&(visibility==='all'||entry.visibility===visibility);});return[...result].sort((a,b)=>sort==='company'?a.company.localeCompare(b.company):sort==='category'?categoryLabel(a.category).localeCompare(categoryLabel(b.category)):a.rank-b.rank);},[entries,normalizedSearch,category,campaign,source,visibility,sort]);
 useEffect(()=>{const params=new URLSearchParams();if(search.trim())params.set('search',search.trim());if(category!=='all')params.set('category',category);if(campaign!=='all')params.set('campaign',campaign);if(source!=='all')params.set('source',source);if(visibility!=='all')params.set('visibility',visibility);if(sort!=='relevance')params.set('sort',sort);const next=params.toString();if(next!==searchParams.toString())router.replace(`${pathname}${next?`?${next}`:''}`,{scroll:false});},[search,category,campaign,source,visibility,sort,pathname,router,searchParams]);
 useEffect(()=>{if(!selected)return;const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape')setSelected(null);};document.addEventListener('keydown',onKeyDown);return()=>document.removeEventListener('keydown',onKeyDown);},[selected]);
 function clear(){setSearch('');setCategory('all');setCampaign('all');setSource('all');setVisibility('all');setSort('relevance');}
 const active=Boolean(search||category!=='all'||campaign!=='all'||source!=='all'||visibility!=='all');
 function sourceHref(entry:BoycottEntry){const params=new URLSearchParams({name:entry.source||'Documented source'});if(entry.sourceUrl)params.set('url',entry.sourceUrl);return `/boycott/source?${params.toString()}`;}
 return <div className={styles.explorer}>
  <div className={styles.searchPanel}>
   <div className={styles.searchBox}><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 5 5"/></svg><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search companies, products, brands…" aria-label="Search companies, products, or brands" />{search&&<button className={styles.clearSearch} onClick={()=>setSearch('')} aria-label="Clear search">×</button>}</div>
   <div className={styles.filterHeading}><span>Filters</span>{active&&<button onClick={clear}>Clear all</button>}</div>
   <div className={styles.filterPanel}>
    <label>Category<select value={category} onChange={e=>setCategory(e.target.value as BoycottCategory|'all')}><option value="all">All categories</option>{categories.map(value=><option key={value} value={value}>{CATEGORY_LABELS[value as BoycottCategory]??value}</option>)}</select></label>
    <label>Visibility<select value={visibility} onChange={e=>setVisibility(e.target.value as BoycottVisibility|'all')}><option value="all">All visibility levels</option><option value="very-high">Very high</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label>
    <label>Campaign<select value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="all">All classifications</option>{campaigns.map(value=><option key={value} value={value}>{value}</option>)}</select></label>
    <label>Source<select value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{sources.map(value=><option key={value} value={value}>{value}</option>)}</select></label>
   </div>
   {active&&<div className={styles.activeFilters}><span>{filtered.length.toLocaleString()} results</span>{category!=='all'&&<button onClick={()=>setCategory('all')}>{CATEGORY_LABELS[category]} ×</button>}{visibility!=='all'&&<button onClick={()=>setVisibility('all')}>{visibilityLabel(visibility)} visibility ×</button>}{campaign!=='all'&&<button onClick={()=>setCampaign('all')}>{campaign} ×</button>}{source!=='all'&&<button onClick={()=>setSource('all')}>{source} ×</button>}{search&&<button onClick={()=>setSearch('')}>“{search}” ×</button>}</div>}
  </div>
  <div className={styles.categorySummary}><span>Categories</span><strong>{categories.length}</strong><div>{categories.map(value=><button key={value} className={category===value?styles.categoryActive:''} onClick={()=>setCategory(value as BoycottCategory)}>{CATEGORY_LABELS[value as BoycottCategory]??value}</button>)}</div></div>
  <div className={styles.resultHeader}><div><span className={styles.resultEyebrow}>Research index</span><h2>Companies &amp; products</h2></div><div className={styles.resultControls}><strong>{filtered.length.toLocaleString()} <span>of {entries.length.toLocaleString()}</span></strong><label className={styles.sortControl}><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort results"><option value="relevance">Visibility</option><option value="company">Company</option><option value="category">Category</option></select></label></div></div>
  {filtered.length===0?<div className={styles.empty}><strong>No companies found</strong><p>Try another company, product, or filter combination.</p><button onClick={clear}>Clear filters</button></div>:<div className={styles.tableWrap}><table><caption className="sr-only">Boycott research database</caption><colgroup><col/><col/><col/><col/><col/></colgroup><thead><tr><th scope="col">#</th><th scope="col">Company</th><th scope="col">Product / Brand</th><th scope="col">Why boycotted</th><th scope="col">Source</th></tr></thead><tbody>{filtered.map(entry=><tr key={entry.id} onClick={()=>setSelected(entry)} tabIndex={0} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(entry)}}}><td className={styles.rank} data-label="#">{entry.rank}</td><td data-label="Company"><div className={styles.company}><Logo entry={entry}/><div><strong>{entry.company}</strong><span className={styles.visibility}>{visibilityLabel(entry.visibility)} visibility</span></div></div></td><td data-label="Product / Brand"><div className={styles.cellText}>{entry.product||'—'}</div></td><td data-label="Why boycotted"><div className={styles.reason} title={entry.reason}>{entry.reason||'Reason not provided by the cited source.'}</div></td><td data-label="Source"><div className={styles.sourceCell}>{entry.source||'Documented entry'}{entry.source&&<a href={sourceHref(entry)} onClick={event=>event.stopPropagation()}>View source ↗</a>}</div></td></tr>)}</tbody></table></div>}
  {selected&&<div className={styles.overlay} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><aside className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="company-detail-title"><button className={styles.close} onClick={()=>setSelected(null)} aria-label="Close company details">×</button><div className={styles.drawerCompany}><Logo entry={selected}/><div><span>Company record · Rank {selected.rank}</span><h3 id="company-detail-title">{selected.company}</h3></div></div><dl><div><dt>Consumer visibility</dt><dd>{visibilityLabel(selected.visibility)}</dd></div><div><dt>Product / Brand</dt><dd>{selected.product||'Not specified'}</dd></div><div><dt>Category</dt><dd>{categoryLabel(selected.category)}</dd></div><div><dt>Why boycotted</dt><dd>{selected.reason||'Reason not provided by the cited source.'}</dd></div><div><dt>Classification</dt><dd>{selected.campaignType||'Not specified'}</dd></div><div><dt>Source</dt><dd>{selected.source||'Not specified'}</dd></div></dl>{selected.source&&<a className={styles.sourceLink} href={sourceHref(selected)}>Open source ↗</a>}</aside></div>}
 </div>;
}
